# Generated by Django 2.1.2 on 2018-10-10 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20181010_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbuy',
            name='moviename',
            field=models.CharField(choices=[('IM', 'IRONMAN'), ('HCS', 'HOME COMING SPIDERMAN'), ('TGF', 'THE GODFATHER'), ('MI:F', 'MISSION IMPOSSIBLE FALLOUT'), ('FF', 'FAST-FIVE'), ('GG', 'GONE GIRL'), ('LO', 'LOGAN'), ('SW', 'STARWARS'), ('IN', 'INCEPTION')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
