# Generated by Django 2.1.2 on 2018-10-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20181010_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportsbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsname', models.CharField(choices=[('OL', 'OLYMPICS'), ('LA', 'LALIGA'), ('IPL', 'IPL'), ('NBA', 'NBA'), ('PK', 'PRO-KHABADDI'), ('UFEA', 'UFEA')], max_length=4)),
                ('sdate', models.DateField()),
                ('sno', models.IntegerField()),
            ],
        ),
    ]
