# Generated by Django 2.1.2 on 2018-10-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_sportsbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concname', models.CharField(choices=[('EDC', 'EDC'), ('MF', 'MAGNETIC FIELD'), ('SB', 'SUN BURN'), ('SS', 'SuperSonic'), ('GC', 'GLOBAL CITIZEN')], max_length=4)),
                ('cdate', models.DateField()),
                ('cno', models.IntegerField()),
            ],
        ),
    ]
