# Generated by Django 2.1.2 on 2018-10-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_concertbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbuy',
            name='ttheatre',
            field=models.CharField(choices=[('I', 'INOX'), ('P', 'PVR'), ('C', 'CITY-PRIDE'), ('PG', 'PVR GOLD')], max_length=3),
        ),
    ]
