# Generated by Django 2.1.2 on 2018-10-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20181016_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertbuy',
            name='concname',
            field=models.CharField(choices=[('EDC', 'EDC'), ('MF', 'MAGNETIC FIELD'), ('SB', 'SUN BURN'), ('SS', 'SUPER SONIC'), ('GC', 'GLOBAL CITIZEN')], max_length=4),
        ),
    ]
